// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imserver.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Command;
@class ContentMessage;
@class Conversation;
@class ConversationList;
@class CustomMessage;
@class FileMessage;
@class GifMessage;
@class GroupMember;
@class GroupMemberList;
@class ImageMessage;
@class LocationMessage;
@class LoggedUser;
@class MentionDetails;
@class Message;
@class MessageList;
@class NewsMessage;
@class Notification;
@class Status;
@class TextMessage;
@class VoiceMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SyncMessageType

/**
 * *
 * 同步消息类型
 **/
typedef GPB_ENUM(SyncMessageType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  SyncMessageType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 传入消息ID 向前同步 */
  SyncMessageType_Forward = 0,

  /** 传入消息ID 向后同步 */
  SyncMessageType_Backward = 1,
};

GPBEnumDescriptor *SyncMessageType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SyncMessageType_IsValidValue(int32_t value);

#pragma mark - Enum Platform

/**
 * *
 * 平台类型
 **/
typedef GPB_ENUM(Platform) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Platform_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Platform_Android = 0,
  Platform_Ios = 1,
  Platform_Web = 2,
  Platform_Pc = 3,
  Platform_Symbian = 4,
  Platform_Linux = 5,
  Platform_Blackberry = 6,
  Platform_Windowsmobile = 7,
  Platform_Palm = 8,
};

GPBEnumDescriptor *Platform_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Platform_IsValidValue(int32_t value);

#pragma mark - Enum MessageType

/**
 * *
 * 消息类型
 **/
typedef GPB_ENUM(MessageType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MessageType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 内容类消息 */
  MessageType_Content = 0,

  /** 状态类消息 */
  MessageType_Status = 1,

  /** 命令类消息 */
  MessageType_Command = 2,

  /** 通知类消息 */
  MessageType_Notification = 3,
};

GPBEnumDescriptor *MessageType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MessageType_IsValidValue(int32_t value);

#pragma mark - ImserverRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ImserverRoot : GPBRootObject
@end

#pragma mark - UserBadgeRequest

typedef GPB_ENUM(UserBadgeRequest_FieldNumber) {
  UserBadgeRequest_FieldNumber_Badge = 1,
};

GPB_FINAL @interface UserBadgeRequest : GPBMessage

@property(nonatomic, readwrite) uint32_t badge;

@end

#pragma mark - GroupMemberListRequest

typedef GPB_ENUM(GroupMemberListRequest_FieldNumber) {
  GroupMemberListRequest_FieldNumber_GroupId = 1,
  GroupMemberListRequest_FieldNumber_MemberIdsArray = 2,
};

GPB_FINAL @interface GroupMemberListRequest : GPBMessage

/**
 * *
 * 群ID
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/**
 * *
 * memberIds 为空使返回群组全部成员
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *memberIdsArray;
/** The number of items in @c memberIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger memberIdsArray_Count;

@end

#pragma mark - MessageByIdRequest

typedef GPB_ENUM(MessageByIdRequest_FieldNumber) {
  MessageByIdRequest_FieldNumber_MessageId = 1,
};

GPB_FINAL @interface MessageByIdRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@end

#pragma mark - FileUploadRequest

GPB_FINAL @interface FileUploadRequest : GPBMessage

@end

#pragma mark - RealtimeMessageRequest

GPB_FINAL @interface RealtimeMessageRequest : GPBMessage

@end

#pragma mark - LoginRequest

typedef GPB_ENUM(LoginRequest_FieldNumber) {
  LoginRequest_FieldNumber_AppId = 1,
  LoginRequest_FieldNumber_UserId = 2,
  LoginRequest_FieldNumber_Token = 3,
  LoginRequest_FieldNumber_Platform = 4,
  LoginRequest_FieldNumber_OsVersion = 5,
  LoginRequest_FieldNumber_DeviceToken = 6,
  LoginRequest_FieldNumber_SdkVersion = 7,
  LoginRequest_FieldNumber_Brand = 8,
};

/**
 * *
 * 登录请求
 **/
GPB_FINAL @interface LoginRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 用户平台 */
@property(nonatomic, readwrite) Platform platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

/** 设备标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;

/** SDK信息， 如： 1.1.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

@end

/**
 * Fetches the raw value of a @c LoginRequest's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LoginRequest_Platform_RawValue(LoginRequest *message);
/**
 * Sets the raw value of an @c LoginRequest's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLoginRequest_Platform_RawValue(LoginRequest *message, int32_t value);

#pragma mark - LoggedUser

typedef GPB_ENUM(LoggedUser_FieldNumber) {
  LoggedUser_FieldNumber_AppId = 1,
  LoggedUser_FieldNumber_UserId = 2,
  LoggedUser_FieldNumber_SessionId = 3,
  LoggedUser_FieldNumber_Platform = 4,
  LoggedUser_FieldNumber_OsVersion = 5,
  LoggedUser_FieldNumber_SdkVersion = 6,
  LoggedUser_FieldNumber_Brand = 7,
  LoggedUser_FieldNumber_LoggedTime = 8,
};

/**
 * *
 * 登录用户信息
 **/
GPB_FINAL @interface LoggedUser : GPBMessage

@property(nonatomic, readwrite) uint64_t appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** android | ios | ... */
@property(nonatomic, readwrite) Platform platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

/** SDK信息， 如： 1.1.0 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

@property(nonatomic, readwrite) uint64_t loggedTime;

@end

/**
 * Fetches the raw value of a @c LoggedUser's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LoggedUser_Platform_RawValue(LoggedUser *message);
/**
 * Sets the raw value of an @c LoggedUser's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLoggedUser_Platform_RawValue(LoggedUser *message, int32_t value);

#pragma mark - LogoutRequest

/**
 * *
 * 登出请求
 **/
GPB_FINAL @interface LogoutRequest : GPBMessage

@end

#pragma mark - HeartbeatRequest

typedef GPB_ENUM(HeartbeatRequest_FieldNumber) {
  HeartbeatRequest_FieldNumber_Interval = 1,
};

/**
 * *
 * 发送心跳请求
 **/
GPB_FINAL @interface HeartbeatRequest : GPBMessage

/**
 * *
 * 心跳间隔, 单位：秒
 **/
@property(nonatomic, readwrite) uint64_t interval;

@end

#pragma mark - MuteConversationRequest

typedef GPB_ENUM(MuteConversationRequest_FieldNumber) {
  MuteConversationRequest_FieldNumber_ConversationType = 1,
  MuteConversationRequest_FieldNumber_Target = 2,
  MuteConversationRequest_FieldNumber_Mute = 3,
};

/**
 * *
 * 会话静音设置
 **/
GPB_FINAL @interface MuteConversationRequest : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *target;

/** 是否静音 */
@property(nonatomic, readwrite) BOOL mute;

@end

#pragma mark - StickyConversationRequest

typedef GPB_ENUM(StickyConversationRequest_FieldNumber) {
  StickyConversationRequest_FieldNumber_ConversationType = 1,
  StickyConversationRequest_FieldNumber_Target = 2,
  StickyConversationRequest_FieldNumber_Sticky = 3,
};

/**
 * *
 * 会话置顶设置
 **/
GPB_FINAL @interface StickyConversationRequest : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *target;

/** 是否置顶 */
@property(nonatomic, readwrite) BOOL sticky;

@end

#pragma mark - RemoveConversationRequest

typedef GPB_ENUM(RemoveConversationRequest_FieldNumber) {
  RemoveConversationRequest_FieldNumber_ConversationType = 1,
  RemoveConversationRequest_FieldNumber_TargetId = 2,
};

/**
 * *
 * 删除会话请求
 **/
GPB_FINAL @interface RemoveConversationRequest : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/** 对端ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@end

#pragma mark - ConversationListRequest

typedef GPB_ENUM(ConversationListRequest_FieldNumber) {
  ConversationListRequest_FieldNumber_Timestamp = 1,
};

/**
 * *
 * 同步会话请求
 **/
GPB_FINAL @interface ConversationListRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t timestamp;

@end

#pragma mark - LatestConversationMessageRequest

typedef GPB_ENUM(LatestConversationMessageRequest_FieldNumber) {
  LatestConversationMessageRequest_FieldNumber_ConversationType = 1,
  LatestConversationMessageRequest_FieldNumber_TargetId = 2,
  LatestConversationMessageRequest_FieldNumber_Timestamp = 3,
  LatestConversationMessageRequest_FieldNumber_PageSize = 5,
};

GPB_FINAL @interface LatestConversationMessageRequest : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/** 对端ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) uint64_t timestamp;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

#pragma mark - SyncConversationMessageRequest

typedef GPB_ENUM(SyncConversationMessageRequest_FieldNumber) {
  SyncConversationMessageRequest_FieldNumber_Type = 1,
  SyncConversationMessageRequest_FieldNumber_ConversationType = 2,
  SyncConversationMessageRequest_FieldNumber_TargetId = 3,
  SyncConversationMessageRequest_FieldNumber_MessageId = 4,
  SyncConversationMessageRequest_FieldNumber_PageSize = 5,
};

/**
 * *
 * 根据消息ID同步会话消息请求
 **/
GPB_FINAL @interface SyncConversationMessageRequest : GPBMessage

/** 同步类型 */
@property(nonatomic, readwrite) SyncMessageType type;

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/** 对端ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

/**
 * Fetches the raw value of a @c SyncConversationMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SyncConversationMessageRequest_Type_RawValue(SyncConversationMessageRequest *message);
/**
 * Sets the raw value of an @c SyncConversationMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSyncConversationMessageRequest_Type_RawValue(SyncConversationMessageRequest *message, int32_t value);

#pragma mark - SyncConversationUpdateMessageRequest

typedef GPB_ENUM(SyncConversationUpdateMessageRequest_FieldNumber) {
  SyncConversationUpdateMessageRequest_FieldNumber_Type = 1,
  SyncConversationUpdateMessageRequest_FieldNumber_ConversationType = 2,
  SyncConversationUpdateMessageRequest_FieldNumber_TargetId = 3,
  SyncConversationUpdateMessageRequest_FieldNumber_Timestamp = 4,
  SyncConversationUpdateMessageRequest_FieldNumber_PageSize = 5,
};

/**
 * *
 * 根据消息最后更新时间同步会话消息请求
 **/
GPB_FINAL @interface SyncConversationUpdateMessageRequest : GPBMessage

/** 同步类型 */
@property(nonatomic, readwrite) SyncMessageType type;

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/** 对端ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

@property(nonatomic, readwrite) uint64_t timestamp;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

/**
 * Fetches the raw value of a @c SyncConversationUpdateMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SyncConversationUpdateMessageRequest_Type_RawValue(SyncConversationUpdateMessageRequest *message);
/**
 * Sets the raw value of an @c SyncConversationUpdateMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSyncConversationUpdateMessageRequest_Type_RawValue(SyncConversationUpdateMessageRequest *message, int32_t value);

#pragma mark - SyncConversationDateMessageRequest

typedef GPB_ENUM(SyncConversationDateMessageRequest_FieldNumber) {
  SyncConversationDateMessageRequest_FieldNumber_ConversationType = 1,
  SyncConversationDateMessageRequest_FieldNumber_TargetId = 2,
  SyncConversationDateMessageRequest_FieldNumber_DayNum = 3,
  SyncConversationDateMessageRequest_FieldNumber_PageNum = 4,
  SyncConversationDateMessageRequest_FieldNumber_PageSize = 5,
};

/**
 * *
 * 同步最近几天的会话消息请求
 **/
GPB_FINAL @interface SyncConversationDateMessageRequest : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/** 对端ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

/** 同步天数 */
@property(nonatomic, readwrite) uint32_t dayNum;

@property(nonatomic, readwrite) uint32_t pageNum;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

#pragma mark - SyncMessageRequest

typedef GPB_ENUM(SyncMessageRequest_FieldNumber) {
  SyncMessageRequest_FieldNumber_Type = 1,
  SyncMessageRequest_FieldNumber_MessageId = 2,
  SyncMessageRequest_FieldNumber_PageSize = 3,
};

/**
 * *
 * 根据消息ID同步消息请求
 **/
GPB_FINAL @interface SyncMessageRequest : GPBMessage

/** 同步类型 */
@property(nonatomic, readwrite) SyncMessageType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

/**
 * Fetches the raw value of a @c SyncMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SyncMessageRequest_Type_RawValue(SyncMessageRequest *message);
/**
 * Sets the raw value of an @c SyncMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSyncMessageRequest_Type_RawValue(SyncMessageRequest *message, int32_t value);

#pragma mark - SyncUpdateMessageRequest

typedef GPB_ENUM(SyncUpdateMessageRequest_FieldNumber) {
  SyncUpdateMessageRequest_FieldNumber_Type = 1,
  SyncUpdateMessageRequest_FieldNumber_Timestamp = 2,
  SyncUpdateMessageRequest_FieldNumber_PageSize = 3,
};

/**
 * *
 * 根据消息最后更新时间同步消息请求
 **/
GPB_FINAL @interface SyncUpdateMessageRequest : GPBMessage

/** 同步类型 */
@property(nonatomic, readwrite) SyncMessageType type;

/** 消息的更新时间戳 */
@property(nonatomic, readwrite) uint64_t timestamp;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

/**
 * Fetches the raw value of a @c SyncUpdateMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SyncUpdateMessageRequest_Type_RawValue(SyncUpdateMessageRequest *message);
/**
 * Sets the raw value of an @c SyncUpdateMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSyncUpdateMessageRequest_Type_RawValue(SyncUpdateMessageRequest *message, int32_t value);

#pragma mark - SyncDateMessageRequest

typedef GPB_ENUM(SyncDateMessageRequest_FieldNumber) {
  SyncDateMessageRequest_FieldNumber_DayNum = 3,
  SyncDateMessageRequest_FieldNumber_PageNum = 4,
  SyncDateMessageRequest_FieldNumber_PageSize = 5,
};

/**
 * *
 * 同步最近几天的消息请求
 **/
GPB_FINAL @interface SyncDateMessageRequest : GPBMessage

/** 同步天数 */
@property(nonatomic, readwrite) uint32_t dayNum;

@property(nonatomic, readwrite) uint32_t pageNum;

@property(nonatomic, readwrite) uint32_t pageSize;

@end

#pragma mark - SendMessageRequest

typedef GPB_ENUM(SendMessageRequest_FieldNumber) {
  SendMessageRequest_FieldNumber_ConversationType = 1,
  SendMessageRequest_FieldNumber_Type = 2,
  SendMessageRequest_FieldNumber_Receiver = 3,
  SendMessageRequest_FieldNumber_Command = 4,
  SendMessageRequest_FieldNumber_ContentMessage = 5,
  SendMessageRequest_FieldNumber_Status = 6,
  SendMessageRequest_FieldNumber_Extra = 15,
};

typedef GPB_ENUM(SendMessageRequest_Content_OneOfCase) {
  SendMessageRequest_Content_OneOfCase_GPBUnsetOneOfCase = 0,
  SendMessageRequest_Content_OneOfCase_Command = 4,
  SendMessageRequest_Content_OneOfCase_ContentMessage = 5,
  SendMessageRequest_Content_OneOfCase_Status = 6,
};

/**
 * *
 * 上行消息
 *
 * 服务端接收之后需要经过加工、处理然后做持久化和在线下发
 **/
GPB_FINAL @interface SendMessageRequest : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/**
 *
 * 消息类型:
 * CONTENT,STATUS,COMMAND
 **/
@property(nonatomic, readwrite) MessageType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *receiver;

@property(nonatomic, readonly) SendMessageRequest_Content_OneOfCase contentOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) Command *command;

@property(nonatomic, readwrite, strong, null_resettable) ContentMessage *contentMessage;

@property(nonatomic, readwrite, strong, null_resettable) Status *status;

/** 额外扩展字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@end

/**
 * Fetches the raw value of a @c SendMessageRequest's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SendMessageRequest_Type_RawValue(SendMessageRequest *message);
/**
 * Sets the raw value of an @c SendMessageRequest's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSendMessageRequest_Type_RawValue(SendMessageRequest *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'content'.
 **/
void SendMessageRequest_ClearContentOneOfCase(SendMessageRequest *message);

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_ConversationType = 1,
  Message_FieldNumber_Id_p = 2,
  Message_FieldNumber_Type = 3,
  Message_FieldNumber_Sender = 4,
  Message_FieldNumber_SendTime = 5,
  Message_FieldNumber_Target = 6,
  Message_FieldNumber_Notification = 7,
  Message_FieldNumber_ContentMessage = 8,
  Message_FieldNumber_Status = 9,
  Message_FieldNumber_DispatTime = 10,
  Message_FieldNumber_Extra = 15,
};

typedef GPB_ENUM(Message_Content_OneOfCase) {
  Message_Content_OneOfCase_GPBUnsetOneOfCase = 0,
  Message_Content_OneOfCase_Notification = 7,
  Message_Content_OneOfCase_ContentMessage = 8,
  Message_Content_OneOfCase_Status = 9,
};

/**
 * *
 * 下行消息
 *
 * 实时接收到的消息， 客户端接收之后需要经过加工、处理并存储为本地消息模型
 **/
GPB_FINAL @interface Message : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationType;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/**
 *
 * 消息类型:
 * CONTENT,STATUS,NOTIFICATION
 **/
@property(nonatomic, readwrite) MessageType type;

/** 发送人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

/** 发送时间 */
@property(nonatomic, readwrite) uint64_t sendTime;

/** 接收端ID， 单聊时为接受者userId， 群聊时为群组id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *target;

@property(nonatomic, readonly) Message_Content_OneOfCase contentOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) Notification *notification;

@property(nonatomic, readwrite, strong, null_resettable) ContentMessage *contentMessage;

@property(nonatomic, readwrite, strong, null_resettable) Status *status;

/** 服务器下发时间 */
@property(nonatomic, readwrite) uint64_t dispatTime;

/** 额外扩展字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@end

/**
 * Fetches the raw value of a @c Message's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Message_Type_RawValue(Message *message);
/**
 * Sets the raw value of an @c Message's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMessage_Type_RawValue(Message *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'content'.
 **/
void Message_ClearContentOneOfCase(Message *message);

#pragma mark - ContentMessage

typedef GPB_ENUM(ContentMessage_FieldNumber) {
  ContentMessage_FieldNumber_ReceiptRequired = 1,
  ContentMessage_FieldNumber_Type = 2,
  ContentMessage_FieldNumber_UpdateTime = 3,
  ContentMessage_FieldNumber_Recalled = 4,
  ContentMessage_FieldNumber_Read = 5,
  ContentMessage_FieldNumber_ReadBitMaskArray = 6,
  ContentMessage_FieldNumber_GroupSnapshotArray = 7,
  ContentMessage_FieldNumber_PushTitle = 8,
  ContentMessage_FieldNumber_PushContent = 9,
  ContentMessage_FieldNumber_Text = 11,
  ContentMessage_FieldNumber_Image = 12,
  ContentMessage_FieldNumber_Gif = 13,
  ContentMessage_FieldNumber_Voice = 14,
  ContentMessage_FieldNumber_News = 15,
  ContentMessage_FieldNumber_File = 16,
  ContentMessage_FieldNumber_Location = 17,
  ContentMessage_FieldNumber_Custom = 18,
};

typedef GPB_ENUM(ContentMessage_Content_OneOfCase) {
  ContentMessage_Content_OneOfCase_GPBUnsetOneOfCase = 0,
  ContentMessage_Content_OneOfCase_Text = 11,
  ContentMessage_Content_OneOfCase_Image = 12,
  ContentMessage_Content_OneOfCase_Gif = 13,
  ContentMessage_Content_OneOfCase_Voice = 14,
  ContentMessage_Content_OneOfCase_News = 15,
  ContentMessage_Content_OneOfCase_File = 16,
  ContentMessage_Content_OneOfCase_Location = 17,
  ContentMessage_Content_OneOfCase_Custom = 18,
};

/**
 * *
 * 内容类消息
 **/
GPB_FINAL @interface ContentMessage : GPBMessage

@property(nonatomic, readwrite) BOOL receiptRequired;

/**
 * *
 * 内容类消息类型
 * MT:Text
 * MT:Image
 * MT:Gif
 * MT:Voice
 * MT:News
 * MT:File
 * MT:Location
 * 其他字符串则代表自定义消息类型
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 更新时间 */
@property(nonatomic, readwrite) uint64_t updateTime;

/** 消息撤回 */
@property(nonatomic, readwrite) BOOL recalled;

/** 消息是否已读 */
@property(nonatomic, readwrite) BOOL read;

/**
 * *
 * 消息已读状态
 * 发送人会收到
 * 单聊:
 *   readBitMask = [ 0 ] 未读
 *   readBitMask = [ 1 ] 已读
 * 群聊:
 *   数组每个元素代表群组成员位,最大表示50人已读状态.
 *   二进制位图由右到左表示成员位
 * 例子:
 *   readBitMask = [ 30, 5]
 *   30       5
 *   11110    101
 *   memberId为2,3,4,5的和51,53的成员已读
 *
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *readBitMaskArray;
/** The number of items in @c readBitMaskArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger readBitMaskArray_Count;

/**
 * *
 * 群成员位图
 * 发送人会收到
 * 二进制位图由右到左表示成员位
 * 例：
 *   userId-memberId
 *   user_1-1
 *   user_2-2
 *   user_3-3
 *   user_4-4
 *   user_5-5
 *
 *   user_6-51
 *   user_8-52
 *   user_9-53
 *
 *   groupSnapshot = [31,7]
 *   二进制位图
 *   11111  111
 *
 *   user_4 user_8 退出群组后
 *   groupSnapshot = [23,5]
 *   二进制位图
 *   10111  101
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *groupSnapshotArray;
/** The number of items in @c groupSnapshotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupSnapshotArray_Count;

/** 推送标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pushTitle;

/** 推送内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pushContent;

@property(nonatomic, readonly) ContentMessage_Content_OneOfCase contentOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) TextMessage *text;

@property(nonatomic, readwrite, strong, null_resettable) ImageMessage *image;

@property(nonatomic, readwrite, strong, null_resettable) GifMessage *gif;

@property(nonatomic, readwrite, strong, null_resettable) VoiceMessage *voice;

@property(nonatomic, readwrite, strong, null_resettable) NewsMessage *news;

@property(nonatomic, readwrite, strong, null_resettable) FileMessage *file;

@property(nonatomic, readwrite, strong, null_resettable) LocationMessage *location;

/** 自定义消息 */
@property(nonatomic, readwrite, strong, null_resettable) CustomMessage *custom;

@end

/**
 * Clears whatever value was set for the oneof 'content'.
 **/
void ContentMessage_ClearContentOneOfCase(ContentMessage *message);

#pragma mark - Status

typedef GPB_ENUM(Status_FieldNumber) {
  Status_FieldNumber_Type = 1,
  Status_FieldNumber_Data_p = 2,
};

/**
 * *
 * 状态消息
 **/
GPB_FINAL @interface Status : GPBMessage

/**
 * *
 * 状态
 * ST:Typing
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@end

#pragma mark - TextMessage

typedef GPB_ENUM(TextMessage_FieldNumber) {
  TextMessage_FieldNumber_Content = 1,
  TextMessage_FieldNumber_MentionDetails = 2,
  TextMessage_FieldNumber_ReceiverMentioned = 3,
};

typedef GPB_ENUM(TextMessage_MentionInfo_OneOfCase) {
  TextMessage_MentionInfo_OneOfCase_GPBUnsetOneOfCase = 0,
  TextMessage_MentionInfo_OneOfCase_MentionDetails = 2,
  TextMessage_MentionInfo_OneOfCase_ReceiverMentioned = 3,
};

/**
 * *
 * 文本消息
 **/
GPB_FINAL @interface TextMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readonly) TextMessage_MentionInfo_OneOfCase mentionInfoOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) MentionDetails *mentionDetails;

@property(nonatomic, readwrite) BOOL receiverMentioned;

@end

/**
 * Clears whatever value was set for the oneof 'mentionInfo'.
 **/
void TextMessage_ClearMentionInfoOneOfCase(TextMessage *message);

#pragma mark - MentionDetails

typedef GPB_ENUM(MentionDetails_FieldNumber) {
  MentionDetails_FieldNumber_MentionAll = 1,
  MentionDetails_FieldNumber_MentionedMembersArray = 2,
};

/**
 * *
 * 群聊 \@ 人信息
 **/
GPB_FINAL @interface MentionDetails : GPBMessage

@property(nonatomic, readwrite) BOOL mentionAll;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *mentionedMembersArray;
/** The number of items in @c mentionedMembersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger mentionedMembersArray_Count;

@end

#pragma mark - ImageMessage

typedef GPB_ENUM(ImageMessage_FieldNumber) {
  ImageMessage_FieldNumber_Content = 1,
  ImageMessage_FieldNumber_Size = 2,
  ImageMessage_FieldNumber_Width = 3,
  ImageMessage_FieldNumber_Height = 4,
  ImageMessage_FieldNumber_URL = 5,
  ImageMessage_FieldNumber_IsOriginal = 6,
};

/**
 * *
 * 图片消息
 **/
GPB_FINAL @interface ImageMessage : GPBMessage

/** base64 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) uint64_t size;

@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) uint32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 是否发送原图 */
@property(nonatomic, readwrite) BOOL isOriginal;

@end

#pragma mark - GifMessage

typedef GPB_ENUM(GifMessage_FieldNumber) {
  GifMessage_FieldNumber_Size = 1,
  GifMessage_FieldNumber_Width = 2,
  GifMessage_FieldNumber_Height = 3,
  GifMessage_FieldNumber_URL = 4,
};

/**
 * *
 * GIF图片消息
 **/
GPB_FINAL @interface GifMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t size;

@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) uint32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - VoiceMessage

typedef GPB_ENUM(VoiceMessage_FieldNumber) {
  VoiceMessage_FieldNumber_Content = 1,
  VoiceMessage_FieldNumber_Duration = 2,
};

/**
 * *
 * 语音消息
 **/
GPB_FINAL @interface VoiceMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) uint32_t duration;

@end

#pragma mark - NewsMessage

typedef GPB_ENUM(NewsMessage_FieldNumber) {
  NewsMessage_FieldNumber_Title = 1,
  NewsMessage_FieldNumber_Description_p = 2,
  NewsMessage_FieldNumber_URL = 3,
  NewsMessage_FieldNumber_LogoURL = 4,
};

/**
 * *
 * 图文消息
 **/
GPB_FINAL @interface NewsMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *logoURL;

@end

#pragma mark - LocationMessage

typedef GPB_ENUM(LocationMessage_FieldNumber) {
  LocationMessage_FieldNumber_Thumb = 1,
  LocationMessage_FieldNumber_Lat = 2,
  LocationMessage_FieldNumber_Lng = 3,
  LocationMessage_FieldNumber_Title = 4,
  LocationMessage_FieldNumber_Address = 5,
};

/**
 * *
 * 位置消息
 **/
GPB_FINAL @interface LocationMessage : GPBMessage

/** 位置缩略图 base64 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumb;

@property(nonatomic, readwrite) double lat;

@property(nonatomic, readwrite) double lng;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@end

#pragma mark - FileMessage

typedef GPB_ENUM(FileMessage_FieldNumber) {
  FileMessage_FieldNumber_Name = 1,
  FileMessage_FieldNumber_Size = 2,
  FileMessage_FieldNumber_URL = 3,
  FileMessage_FieldNumber_MimeType = 4,
};

/**
 * *
 * 文件消息
 **/
GPB_FINAL @interface FileMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) uint64_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimeType;

@end

#pragma mark - CustomMessage

typedef GPB_ENUM(CustomMessage_FieldNumber) {
  CustomMessage_FieldNumber_Data_p = 1,
};

/**
 * *
 * 自定义消息
 **/
GPB_FINAL @interface CustomMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@end

#pragma mark - Notification

typedef GPB_ENUM(Notification_FieldNumber) {
  Notification_FieldNumber_Type = 1,
  Notification_FieldNumber_Data_p = 2,
};

/**
 * *
 * 通知
 **/
GPB_FINAL @interface Notification : GPBMessage

/**
 * *
 * 通知类型
 * NT:GroupCreated
 * NT:GroupDismissed
 * NT:GroupMemberJoined
 * NT:GroupMemberQuited
 * NT:GroupRenamed
 * NT:GroupMemberKicked
 * NT:ConversationMuteUpdated
 * NT:ConversationStickyUpdated
 * NT:ConversationRemoved
 * NT:MessageRecalled
 * NT:MessageRead
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@end

#pragma mark - Command

typedef GPB_ENUM(Command_FieldNumber) {
  Command_FieldNumber_Type = 1,
  Command_FieldNumber_Data_p = 2,
};

/**
 * *
 * 命令
 **/
GPB_FINAL @interface Command : GPBMessage

/**
 * *
 * 命令类型
 * CMD:RecallMessage
 * CMD:ReadMessage
 *
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@end

#pragma mark - Conversation

typedef GPB_ENUM(Conversation_FieldNumber) {
  Conversation_FieldNumber_Type = 1,
  Conversation_FieldNumber_TargetId = 2,
  Conversation_FieldNumber_Sticky = 3,
  Conversation_FieldNumber_Muted = 4,
  Conversation_FieldNumber_Deleted = 5,
};

/**
 * *
 * 会话
 **/
GPB_FINAL @interface Conversation : GPBMessage

/**
 * *
 * 会话类型
 * CT:Private
 * CT:Group
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 对端ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;

/**
 * *
 * 置顶状态
 * 0/时间戳
 * 以时间戳顺序排列置顶顺序
 **/
@property(nonatomic, readwrite) uint64_t sticky;

/**
 * *
 * 静音状态
 **/
@property(nonatomic, readwrite) BOOL muted;

/**
 * *
 * 删除状态
 **/
@property(nonatomic, readwrite) BOOL deleted;

@end

#pragma mark - ConversationList

typedef GPB_ENUM(ConversationList_FieldNumber) {
  ConversationList_FieldNumber_ContentArray = 1,
};

GPB_FINAL @interface ConversationList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Conversation*> *contentArray;
/** The number of items in @c contentArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contentArray_Count;

@end

#pragma mark - MessageList

typedef GPB_ENUM(MessageList_FieldNumber) {
  MessageList_FieldNumber_ContentArray = 1,
};

GPB_FINAL @interface MessageList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *contentArray;
/** The number of items in @c contentArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contentArray_Count;

@end

#pragma mark - GroupMember

typedef GPB_ENUM(GroupMember_FieldNumber) {
  GroupMember_FieldNumber_GroupId = 1,
  GroupMember_FieldNumber_MemberId = 2,
  GroupMember_FieldNumber_UserId = 3,
};

/**
 * *
 * 群组成员信息
 **/
GPB_FINAL @interface GroupMember : GPBMessage

/**
 * *
 * 群组ID
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/**
 * *
 * 群成员ID
 **/
@property(nonatomic, readwrite) uint32_t memberId;

/**
 * *
 * 用户ID
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - GroupMemberList

typedef GPB_ENUM(GroupMemberList_FieldNumber) {
  GroupMemberList_FieldNumber_GroupMembersArray = 1,
};

/**
 * *
 * 群组成员集合
 **/
GPB_FINAL @interface GroupMemberList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupMember*> *groupMembersArray;
/** The number of items in @c groupMembersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupMembersArray_Count;

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_Code = 1,
  Response_FieldNumber_Message = 2,
  Response_FieldNumber_Conversations = 3,
  Response_FieldNumber_Messages = 4,
  Response_FieldNumber_SentMessage = 5,
  Response_FieldNumber_LoggedUser = 6,
  Response_FieldNumber_FileUploadInfo = 7,
  Response_FieldNumber_GroupMemberList = 8,
};

typedef GPB_ENUM(Response_Data_OneOfCase) {
  Response_Data_OneOfCase_GPBUnsetOneOfCase = 0,
  Response_Data_OneOfCase_Conversations = 3,
  Response_Data_OneOfCase_Messages = 4,
  Response_Data_OneOfCase_SentMessage = 5,
  Response_Data_OneOfCase_LoggedUser = 6,
  Response_Data_OneOfCase_FileUploadInfo = 7,
  Response_Data_OneOfCase_GroupMemberList = 8,
};

GPB_FINAL @interface Response : GPBMessage

/**
 * *
 * 0:    成功
 * 1001 ~ 1999: 客户端错误
 * 1001: APP不存在
 * 1002: APP已禁用
 * 1003: 非法用户
 * 1010: 用户不存在
 * 1011: 用户已禁用
 * 1013: 用户Session失效
 * 1014: 参数异常
 * 1015: 服务端异常
 * 2001 ~ 2999: 业务逻辑错误
 * 3001 ~ 3999: 服务端错误
 **/
@property(nonatomic, readwrite) uint32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readonly) Response_Data_OneOfCase dataOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) ConversationList *conversations;

@property(nonatomic, readwrite, strong, null_resettable) MessageList *messages;

@property(nonatomic, readwrite, strong, null_resettable) Message *sentMessage;

/**
 * *
 * 登录接口返回当前登录的用户
 **/
@property(nonatomic, readwrite, strong, null_resettable) LoggedUser *loggedUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileUploadInfo;

@property(nonatomic, readwrite, strong, null_resettable) GroupMemberList *groupMemberList;

@end

/**
 * Clears whatever value was set for the oneof 'data'.
 **/
void Response_ClearDataOneOfCase(Response *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
